name: Build and deploy Docker app  DOCKER HUB

on:
  push:
    branches: [main, staging]
    paths:
      - src/**
      - 'package.json'
      - .github/**

env:
  ME: ${{ME}}
  EXECPATH: ${{secrets.EXECPATH}}
  MARKETING_DB_STRING: ${{secrets.MARKETING_DB_STRING}}
  CLOUDINARY_NAME: ${{secrets. :${{secrets.CLOUDINARY_NAME}}
  CLOUDINARY_KEY: ${{secrets.CLOUDINARY_KEY}}
  CLOUDINARY_SECRET: ${{secrets.CLOUDINARY_SECRET}}
  PORT: ${{secrets.PORT}}
  NODE_ENV: ${{secrets.NODE_ENV}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          dockerfile: ./Dockerfile
          tags: your-dockerhub-username/cddemo:latest
