const advertMessages = [
  //"*Upgrade your storage game with SSDs!*\n Faster, quieter and more efficient than hard drives.\n With less moving parts they are also durable and resistant to shock or vibration making them perfect for laptops on the go.\nPlus, encryption means secure data protection. They are starting from just $35-00 at our shop located upstairs from TM shops.\n Call/whatsapp 0775231426 now for an upgrade you won't regret!",
  
  '*🔥 Original Verbatim Flash Drives — $7 (16GB) | $9 (32GB) | $11 (64GB)*\n\nGenuine Verbatim USB drives — fast, reliable & built to last. Perfect for backups, school work, music, movies & file transfers.\n\n✅ 100% Original\n✅ Plug & Play\n✅ Lifetime durability\n\n📍 *Shop 1, Above TM Pick n Pay Flats, Hwange*\n📞 Call/WhatsApp: 0775231426 / 0781590257\n🛒 Catalogue: https://wa.me/c/263716139808',
  '*🖨️ Printer Consumables — All Major Brands In Stock*\n\nToshiba • Pantum • Xerox • Ricoh • Bizhub • HP • Canon & more\n\nKeep your printers running without downtime. Venta Tech is your one-stop shop for:\n✅ Toner cartridges (heavy-duty & standard)\n✅ Ink refills & cartridges\n✅ Refill toner powder\n✅ Copier master & ink supplies\n✅ Drum units & chips\n\n📍 *Shop 1, Pick n Pay Mall, Hwange* (upstairs from TM, entrance between TM & Post Office)\n📞 Call/WhatsApp: 0775231426',
  //"*Buy an SSD now*\nStill using a Hard Disk Drive (HDD) In 2024🤔\n\nAre your files not worth anything to you❓❓\nSSDs are cheaper 10x faster and more durable.Call us and get yours *Starting from 💲3️⃣5️⃣* (including free installaton of OS and migration of files)",
  '*🖨️ Refill Supplies & Spare Parts — In Stock Now*\n\nSave big on printer running costs with our refill range:\n\n✅ Toner powder (all grades)\n✅ Refill ink (bulk & bottles)\n✅ Toner cartridge reset chips\n✅ Imaging drums\n✅ Magnetic drums\n\n📍 *Shop 1, TM Pick n Pay Mall, Hwange* — upstairs from TM, entrance between TM & Post Office (behind new BancABC)\n📞 Call/WhatsApp: 0775231426',
  `*📡 STARLINK INSTALLATION & SETUP — Done Right, First Time*\n\nGot a Starlink kit but not sure how to set it up? Venta Tech's certified team has you covered.\n\n✅ Professional mounting (roof, pole, wall)\n✅ Configuration & activation\n✅ Network security setup\n✅ Coverage extension (WiFi extenders & mesh)\n✅ Cable management & weatherproofing\n\n📞 Call/WhatsApp: 0775231426\n📍 Venta Tech — Shop 1, TM Pick n Pay Mall, Hwange`,
  
  `*📡 STARLINK KITS — Just $300 (Installation Included!)*\n\nWant fast, reliable internet at your home or business *today*? We deliver, install & activate — all in one visit.\n\n✅ Brand new Starlink kit\n✅ Same-day delivery & installation\n✅ Professional mounting & configuration\n✅ Speeds up to 180 Mbps\n✅ Works anywhere — even in remote areas\n\n💰 *All-in price: $300* (kit + installation)\n\n📞 Call/WhatsApp: 0775231426 — order now & be online today!\n📍 Venta Tech — Shop 1, TM Pick n Pay Mall, Hwange`,
  `*📹 CCTV Camera Installation — Protect What Matters Most*\n\nKeep an eye on your home, shop, or business 24/7 — from anywhere in the world.\n\n✅ HD & 4K surveillance cameras\n✅ Remote viewing on phone or PC\n✅ Motion detection alerts\n✅ Night vision (infrared)\n✅ Facial recognition technology\n✅ Cloud & local storage options\n\n🛠️ Full installation, cabling & setup by our experts.\n\n📞 Call/WhatsApp: 0775231426\n📍 Venta Tech — Shop 1, TM Pick n Pay Mall, Hwange`,
  `*💻 Computer Repairs & Printer Servicing — Fast, Reliable, Affordable*\n\nSlow laptop? Broken printer? Cracked screen? Our certified techs fix it all.\n\n✅ Hardware repairs (screens, batteries, keyboards, motherboards)\n✅ Software troubleshooting & OS reinstalls\n✅ Virus & malware removal\n✅ Data recovery & backup\n✅ Printer servicing & deep cleaning\n✅ Network & WiFi setup\n\n⚡ *Quick turnaround — most repairs done same day*\n\n📞 Call/WhatsApp: 0775231426\n📍 Venta Tech — Shop 1, TM Pick n Pay Mall, Hwange`,
  
  //'📶🖨️ FREE WIFI AVAILABLE! 📚\n Need to print assignments, documents, or forms? Students and community welcome!\nConnect & print easily, just come to any of our Venta shops (Total Baobab Service station, or PickN Pay Flats). \Get additional free WIFI by liking our page\nhttps://www.facebook.com/millenniumprinters.zw/',
  `*🎯 Make Your Storefront POP — 3D Signs & Branding*\n\nTurn passing shoppers into loyal customers with bold, eye-catching signage that stands out day & night.\n\n✅ Backlit 3D logo signs\n✅ Stainless steel & acrylic letters\n✅ Light boxes & illuminated displays\n✅ Custom front displays\n✅ Vinyl wraps & full exterior branding\n\n🎨 *Free design consultation* — we handle concept, build & installation.\n\n📞 Call/WhatsApp: 0775231426\n📍 Venta Tech — Shop 1, TM Pick n Pay Mall, Hwange`,
  '*📒 Serialised Receipt Books — Full Colour, Custom Branded*\n\nLook professional with custom-printed business stationery from Venta Tech. Fast turnaround, sharp print quality, your logo & details on every page.\n\n📑 *Business Documents:*\n✅ Serialised receipt books (full colour)\n✅ Invoice books\n✅ Log books\n✅ Report books\n✅ Delivery notes & quotation books\n\n📚 *Also Available:* Dictionaries\n\n📍 *Shop 1, Above TM Pick n Pay Flats, Hwange*\n📞 Call/WhatsApp: 0775231426',
  `*📶 WiFi Extenders — Just $38 (Plug & Play!)*\n\nTired of WiFi dead zones in your home or office? Boost your signal in seconds — no tech skills needed.\n\n✅ Simple plug & play setup (under 2 minutes)\n✅ Works perfectly with *Starlink* to extend coverage\n✅ Eliminates dead zones in bedrooms, garages & outdoor areas\n✅ Fast & stable connection\n✅ Compatible with any router\n\n💰 *Only $38* — limited stock!\n\n📞 Call/WhatsApp: 0775231426\n📍 Venta Tech — Shop 1, TM Pick n Pay Mall, Hwange`,
];

module.exports = advertMessages;
