const advertMessages = [
  //"*Upgrade your storage game with SSDs!*\n Faster, quieter and more efficient than hard drives.\n With less moving parts they are also durable and resistant to shock or vibration making them perfect for laptops on the go.\nPlus, encryption means secure data protection. They are starting from just $35-00 at our shop located upstairs from TM shops.\n Call/whatsapp 0775231426 now for an upgrade you won't regret!",
  "Looking for high-quality printing supplies? Look no further than Venta Tech! \nFind everything you need, \nincluding toner powder and refill ink to keep your printer running smoothly. Plus, say goodbye to costly replacements with our toner cartridge reset chips - they'll have you saving money in no time. And don't forget about the essential imaging drum and magnetic drum* that provide stunning print quality every time.\nVisit us at Shop1 TM mall today (located upstairs from TM)! Just look for our entrance between Post office and TM behind new Banc ABC. #PrintingSupplies #VentaTech ",
  "*$7 32GB $8 64GB* Original Kingston data traveller flash drive \n Call/Whatsapp 0775231426/ 263781590257\n\n LOCATION SHOP NO. 1 Above TM Pick N Pay Flats Hwange \n App or Call 0775231426",
  "Toshiba, Pantum ,Xerox, Ricoh, Bizhub? Looking for top-quality printer consumables that won't let you down? Look no further than Venta tech - your one-stop-shop for all things printing. From heavy-duty toner cartridges to ink refills, we've got everything you need to keep your printers running smoothly.We're proud suppliers of some of the most trusted brands in the industry, such as Ricoh, Bizhub, Xeroxnd Toshib And with our wide range of products up for grabs - including refill toner powder and copier master & ink supplies - there`s truly something here for everyone.\nSo why wait? Give us a call or shoot us a message on WhatsApp at 0775231426 today! You'll find our shop conveniently located at fisrt shop at Pick n Pay Mall (upstairs from TM; entrance between TM and Post Office)",
  //"*Buy an SSD now*\nStill using a Hard Disk Drive (HDD) In 2024🤔\n\nAre your files not worth anything to you❓❓\nSSDs are cheaper 10x faster and more durable.Call us and get yours *Starting from 💲3️⃣5️⃣* (including free installaton of OS and migration of files)",
  "*Toner powder,\nRefill ink,\nToner cartridge reset chip,\nImaging drum,\nMagnetic Drum*\nAll available at Venta Tech, Shop1 TM mall( Shops upstairs from TM), entrance is between between Post office and TM (behind new Banc ABC)",

  "💲6️⃣ for 3️⃣2️⃣GB ,💲8️⃣ for 6️⃣4️⃣GB.\n\n*In Stock* \n\nGrab an Original Kingston data traveler flash drive for $6 (32GB) or $8 (64GB) from Shop 1 at TM Shops upstairs.\n\n Look for the entrance between POST and Pick n Pay! Contact us now on call/WhatsApp:\n\n 0️⃣7️⃣7️⃣5️⃣ 2️⃣3️⃣1️⃣ 4️⃣2️⃣6️⃣",
  "*Toner cartridges,Ink Cartridges, Master and ink for heavy duty copiers* , \n Venta tech are the premier suppliers of all printer consumables. *Contact us*  for all major brands of printers, HP , Kyocera, Nashua, Lexmark, Canon , Samsung i.e. *Also available* refill toner powder,cartridges, master & ink for copiers are available. Call or whatsapp *0775231426* or visit our shop at TM Pick n Pay Mall ( Shops above TM *Entrance between TM and Post office*) ",
  " Original printer consumables available at great prices. Visit Venta tech, Shop 1 Baobab Service Station. In stock Hp ,Kyocera,Nashua, Ricoh,Samsung and all other major brands, Call us or whatsapp on 0775 231 426 for enquiries,or visit our shop at Total Baobab Service Station",
  `*CCTV camera installation services*\n\n👮‍♂️  We offer state-of-the-art  surveillance cameras with remote monitoring features and facial recognition technology. Stay safe 24/7 with infrared light capabilities, motion detection alerts, and live feeds accessible from your phone or computer. *Contact us on 0️⃣7️⃣7️⃣5️⃣ 2️⃣3️⃣1️⃣ 4️⃣2️⃣6️⃣ or send a WhatsApp message today!* `,
  `*💻Computer Repairs, Printer Servicing* \n Reliable,Proffessional Computer hardware and Software Repairs by industry experts. \n Please inbox for enquiries`,
  //`🎶Music 🎥 Movies , Softwares\n\n Chose from our wide range of music, movies and softwares.\n\nIf we dont have it yet , we will find it for you.LOCATION SHOP NO. 1 Above TM Pick N Pay Flats Hwange \n App or Call 0️⃣7️⃣7️⃣5️⃣ 2️⃣3️⃣1️⃣ 4️⃣2️⃣6️⃣ or `,
  //"*FASTEST WIFI HOTSPOT IN THE LAND* \n Visit us at \n  VENTA TECH LOCATION: SHOP NO1 Above Pick N Pay Shops (Shops above TM *Entrance between TM and Post*), Hwange   APP or CALL0775231426 Download :\nMovies \n Music \nSoftwares \n   $1 Voucher For 1 hour \n $3 Voucher for 2GB  \n 30 minutes free WiFi for school children in school uniforms",

  "*Serialised Receipt Books In full colour*, Business Documents,VENTA TECH provides proffessionally business documents such as Receipt books,Invoice Books, \n LOCATION SHOP NO. 1 Above TM Pick N Pay Flats Hwange \n App or Call 0775231426 \n For all your \n \n Receipts Books  \nInvoice Books \nLog Books \nReports Books \n 20 pack display books \nA4 Envelopes  \n Rulers \nMathematical sets \nDictionary \nSecondary text books ",
  "*VSAT Internet*, your internet solution for remote areas.\nCall us on 0775231426 and you can have an internet connetcion within 48 hours,literally anywhere , we have unlimited coverage. Ideal for safaris, mines, rural setup etc.Fast reliable internet from Utande:  *Registered Utande reseller*.",
  "*Automated WhatsApp chatbot* Run automatic adverts, automatic replies, bulk messaging, automatic alerts\nWebsite Development\nWeb app development,\nEmail hosting etc... \nCall/Whatsapp 0775231426\nOr visit our offices at  *VENTA TECH LOCATION*: SHOP NO1 Above Pick N Pay Shops (Shops above TM *Entrance between TM and Post*), Hwange ",
  //"📓Are you preparing for exams or struggling with a particular topic? \nExperience the future of Try AskMe the revolutionary AI powered  study app on by simply messaging on WhatsApp. \nIntroducing our new pay-as-you-use model! \nFor only $500, get 55 messages/requests on our AI study application. Get Instant answers, personalized assistance ,notes in your WhatsApp inbox \n Try it here for *FREE* https://bit.ly/AskMeAIChat AskMe_Ai team;"
];

module.exports = advertMessages;
